### ISSUE TITLE
Error when editing Document

### ISSUE THREAD

**Issue by Drakot** [HamidrezaAmz/MagicalPdfEditor#1]
`Permission Denial: writing com.android.providers.downloads.DownloadStorageProvider uri content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2F130%204t.pdf from pid=5340, uid=10113 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()`

To avoid this I had To modify the code when opening a PDF like this

```
  Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("application/pdf");
```

**Comment by HamidrezaAmz** [comment]
If you read the **readme** section completely, I have mentioned that.

> Working with files is restricted in higher android api levels, So if you are working with high level android APIs, be aware of using file provides and needed permissions to work with files, Or you can use SimpleStorage lib to work with files and Android storage.

**Comment by Drakot** [comment]
The permission it's not the issue, its the intent category only. Changing that works like a charm.

**Comment by HamidrezaAmz** [comment]
Can you give me an example or a code snippet?

**Comment by Drakot** [comment]
It happens when opening from the native file manager

![Captura de pantalla 2021-02-06 a las 12 58 32](https://user-images.githubusercontent.com/10567874/107117533-1b1bb980-687b-11eb-963f-a614fad9adc8.png)

Opening the file manager with the code i posted in my first comment works good.

These are the only changes needed.

![Captura de pantalla 2021-02-06 a las 13 01 49](https://user-images.githubusercontent.com/10567874/107117573-85345e80-687b-11eb-86a5-6586783c9d59.png)

I'm using Nexus 5x Api 28 Emulator.

**Comment by HamidrezaAmz** [comment]
I have added this change into repo. 
@Drakot
