### ISSUE TITLE
How to set only one page visible on screen in pdfview?

### ISSUE THREAD

**Issue by vaidik1011** [HamidrezaAmz/MagicalPdfEditor#2]
I want to show only single page of PDF on PDFView on Screen at a time. how to do it?

**Comment by HamidrezaAmz** [comment]
This library uses [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer) for previewing pdf pages, you can use another config for showing single page of pdf on pdfView.
You can find all available options with default values in [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer)
